### PR TITLE
Fix builds on Window platforms

### PR DESCRIPTION
**Pull request by brogdonm**
## Changes in this pull request

There were a few places where builds on a Window's machine were not working. The common issues were:

- Use of the `rm` command, switched over to `rimraf`
- Use of the `cp` command in build scripts, switched to `cpy-cli` tool
- Much of the rollup configuration files were not correctly ensuring paths had `/` in them, which most of the `path.*` calls were converting to the Window's path separator `\`.

I'm new to the rush build setup, so I'm pretty sure I may have caused changes to the lock files that may not be desirable when I "installed" the `cpy-cli` tool. 

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist
- [ ] All applicable changes have been documented
- [ ] Any `TO DO` items (or similar) have been entered as GitHub issues and the link to that issue has been included in a comment

### CODE REVIEW

**Comment by dkozma** [comment]
Thanks for this PR @brogdonm ! Would you be able to sign the CLA when you get a chance?

**Comment by brogdonm** [comment]
> Thanks for this PR @brogdonm ! Would you be able to sign the CLA when you get a chance?

Thanks @dkozma, I'm having legal review the contract, hopefully will have follow up in a couple days.

**Comment by brogdonm** [comment]
I've signed the contract, closing PR and reopening to ensure it has taken.

**Comment by brogdonm** [comment]
@dkozma I have finished all the steps and resolved conflicts (with an additional typo fixed in a build script).

**Comment by brogdonm** [comment]
@dkozma @emensch With the latest merge conflict resolution the new `packages/toolkit/scripts/build.js` is giving me the following error on Windows, not sure what it is at this point:

```
node .\scripts\build.js
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: spawn ./node_modules/.bin/tsc ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:285:19)
    at onErrorNT (node:internal/child_process:485:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
    at onErrorNT (node:internal/child_process:485:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn ./node_modules/.bin/tsc',
  path: './node_modules/.bin/tsc',
  spawnargs: [
    '--project',
    'C:\\src\\GitHub\\c2pa-js\\packages\\toolkit\\tsconfig.json'
  ]
}
```

I have ran the `./node_modules/.bin/tsc --project C:\\src\\GitHub\\c2pa-js\\packages\\toolkit\\tsconfig.json` separately and it works, so not sure why this is a problem when ran from the `node` context.

**Comment by dkozma** [comment]
Thanks for looking into this @brogdonm. My only thought here is since we are getting an `ENOENT`, I wonder if it is resolving the `./node_modules` directory to the wrong location. I wonder if we can solve this by specifying the location as clearly as possible. Please take a look at [this change](https://github.com/contentauth/c2pa-js/compare/dkozma/add-path-to-tsc?expand=1#diff-48254a2d1cf1f5955a9bc916bff9a6f09bd50a62baa9d076691bf6ade537e9f0) and let me know if something like this can help things.

**Comment by brogdonm** [comment]
> Thanks for looking into this @brogdonm. My only thought here is since we are getting an `ENOENT`, I wonder if it is resolving the `./node_modules` directory to the wrong location. I wonder if we can solve this by specifying the location as clearly as possible. Please take a look at [this change](https://github.com/contentauth/c2pa-js/compare/dkozma/add-path-to-tsc?expand=1#diff-48254a2d1cf1f5955a9bc916bff9a6f09bd50a62baa9d076691bf6ade537e9f0) and let me know if something like this can help things.

Yeah, you were on the right path. I looked and `tsc` on Windows is a `PS1` or `CMD` file, so I believe it has to be spawned with a shell context... see 7aa39db for the changes.

**Pull request merged**
